### ISSUE TITLE
additional currencies, collab?

### ISSUE THREAD

**Issue by codinguncut** [kilimchoi/cryptocurrency#3]
Hi Kilim,

thank you so very much for sharing this information.
I have started a fork/similar repo here: https://github.com/codinguncut/cryptocurrency/ 

I'm planning to automate the github stats, and I am also collating text-based analyses from reddit, etc. to track "chatter", sentiment, etc.

Here is a WIP example of reddit chatter vs. market cap, I'll upload the notebook soonish including sentiment analysis.
According to (just) this "naive" analysis, there has been a lot of interest vs. market_cap in monero, siacoin, litecoin, dash in past 10 weeks.

| name | % mentions | % market cap | mentions / market_cap |
|-------|---------------|----------------|---------------------------|
|gridcoin |  1.7% |  0.0% |  6030% |
|pivx |  2.1% |  0.1% |  2648% |
|lykke |  0.8% |  0.1% |  1381% |
|monero |  6.7% |  0.7% |  958% |
|nxt |  0.8% |  0.2% |  530% |
|siacoin |  2.0% |  0.4% |  491% |
|digibyte |  0.9% |  0.2% |  380% |
|dash |  4.7% |  1.3% |  377% |
|zcash |  1.9% |  0.5% |  349% |
|litecoin |  7.0% |  2.2% |  320% |
|nem |  3.8% |  1.7% |  227% |
|factom |  0.5% |  0.2% |  221% |
|dogecoin |  0.6% |  0.3% |  188% |
|stratis |  1.3% |  0.7% |  177% |
|steem |  0.7% |  0.4% |  167% |
|waves |  0.7% |  0.5% |  148% |
|iota |  1.4% |  1.1% |  129% |
|bitshares |  0.8% |  0.8% |  103% |
|ripple |  9.5% |  10.3% |  93% |
|ethereum classic |  1.5% |  1.9% |  78% |
|bitcoin |  24.6% |  39.4% |  62% |
|ethereum |  18.6% |  32.8% |  57% |

Would you be interested in collaborating on this going forward?
Alternatively, would you be interested in adding a few "relevant" currencies even if "bad" (iota, lisk, pivix, nxt) from https://coinmarketcap.com/currencies/, or do you have your reasons for this exact selection?

**Comment by kilimchoi** [comment]
Yes! I'm all for collab! That's exactly why I created this repo! Feel free to make a pr or make suggestions on how we can improve this list! Also you can email me at choikilim1202 AT gmail.com

Looks like you added a lot more data. I think that with the current format, it might look too cluttered to fit all that in one table, but we might be able to create another table within the same repo. What do you think?

**Comment by codinguncut** [comment]
sure, sounds great.
I'll sort out my approach a bit more, and would love to collab then in one way or another.
Johannes

**Comment by codinguncut** [comment]
probably completely over-engineered, but it would be nice if we could keep information in a machine-readable format... could even be MD.
then we could join data from different sources, keyed i.e. by "symbol".

- qualitative information from your table
- github project "health"
- text/web analysis from my notebook
- market cap, trade volume, growth from coin portals

as I said, probably over-engineered, but could lead towards a nice dashboard anyways ;)

**Comment by kilimchoi** [comment]
Can you reach out to me via email mentioned above?
